# -*- coding: utf-8 -*-
"""AttendanceSystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Abe2zoE7xgg1dBx4-LsPw4RLR-rugzAd
"""

#Student Attendance System

teacher = input("Enter teacher name: ")
subject = input("Enter subject name: ")

students = ["Rahul", "Ananya", "Vivek", "Neha", "Arjun", "Simran"]

days = int(input("Enter total number of working days: "))

attendance_record = {}

defaulters = []

top_student = ""
highest_percentage = 0

for student in students:

    print(f"\nEntering attendance for {student}")

    present_days = 0

    for day in range(1, days + 1):

        attendance = input(f"Day {day} attendance (yes/no): ").lower()

        if attendance == "yes":
            present_days += 1

        elif attendance == "no":
            continue

        else:
            print("Invalid input")

    absent_days = days - present_days

    attendance_percentage = (present_days / days) * 100

    if attendance_percentage > 75:
        status = "Good Attendance"

    elif attendance_percentage >= 50:
        status = "Average Attendance"

    else:
        status = "Poor Attendance"

    # Defaulter students
    if attendance_percentage < 75:
        defaulters.append(student)

    # Top attendance student
    if attendance_percentage > highest_percentage:
        highest_percentage = attendance_percentage
        top_student = student

    attendance_record[student] = {
        "Present Days": present_days,
        "Absent Days": absent_days,
        "Attendance Percentage": attendance_percentage,
        "Status": status
    }

print("\n========== ATTENDANCE REPORT ==========")

print("Teacher:", teacher)
print("Subject:", subject)

for student, details in attendance_record.items():

    print(f"\nStudent: {student}")

    print("Present Days:", details["Present Days"])

    print("Absent Days:", details["Absent Days"])

    print(f"Attendance Percentage: {details['Attendance Percentage']:.2f}%")

    print("Status:", details["Status"])

print("\n----- DEFAULTER STUDENTS -----")

if len(defaulters) == 0:
    print("No defaulters")

else:
    for student in defaulters:
        print(student)

print("\n----- TOP ATTENDANCE STUDENT -----")

print(f"{top_student} with {highest_percentage:.2f}% attendance")