# -*- coding: utf-8 -*-
"""Smart Electricity Usage Analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nYNBuT0uEDd11Ai15KfE1TN7Hjx-TWPX
"""

# Smart Electricity Usage Analyzer

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Appliance Data
appliances = ['Fan', 'AC', 'TV', 'Laptop']
units = np.array([100, 200, 150, 50])

# Categories
categories = ['Cooling', 'Cooling', 'Entertainment', 'Computing']

# NumPy Analysis
print("----- ELECTRICITY USAGE ANALYSIS -----")

print("Average Usage:", np.mean(units))

print("Highest Usage:", np.max(units))

print("Lowest Usage:", np.min(units))

# Pandas DataFrame
data = {
    "Appliance": appliances,
    "Category": categories,
    "Units Consumed": units
}

df = pd.DataFrame(data)

# Estimated Cost
df['Estimated Cost'] = df['Units Consumed'] * 6

print("\n----- APPLIANCE DATA -----")
print(df)

# Highest Consuming Appliance
highest = df.loc[df['Units Consumed'].idxmax()]

print("\n----- HIGHEST POWER CONSUMING APPLIANCE -----")
print(highest)

# High Consumption Warning
high_usage = df[df['Units Consumed'] > 100]

print("\n----- HIGH ELECTRICITY CONSUMPTION -----")

if len(high_usage) > 0:
    print(high_usage)

else:
    print("No high electricity consumption detected")

# Appliance Ranking
sorted_df = df.sort_values(by="Units Consumed", ascending=False)

print("\n----- APPLIANCE RANKING -----")
print(sorted_df)

# Total Estimated Cost
total_cost = df['Estimated Cost'].sum()

print(f"\nTotal Estimated Electricity Cost: ₹{total_cost}")

# Bar Graph
plt.bar(appliances, units)

plt.xlabel("Appliances")

plt.ylabel("Units Consumed")

plt.title("Electricity Usage Analysis")

plt.show()

# Pie Chart
plt.pie(units, labels=appliances, autopct='%1.1f%%')

plt.title("Electricity Consumption Share")

plt.show()